Repository Harlem-Launch-Alliance/Catalyst-2, pull requests merged in 2022-10, with the labels that each got.

#114 changed counter type to reduce memory usage
  main/attitude.h
Labels: enhancement, beginner, hacktoberfest-accepted

#116 clarified external contribution rule
  README.md
Labels: documentation

#115 Added detail to pull request template
  pull_request_template.md
Labels: documentation

#119 GPS wait time integration
  main/gps.h
Labels: GPS, hacktoberfest-accepted

#118 Added more logging to IMU failure
  main/gy521_imu.h
Labels: hacktoberfest-accepted

#121 Variable cleanup
  main/apogee.h
  main/attitude.h
  main/main.ino
  main/ringQueue.h
  main/settings.h
  main/utils.h
Labels: enhancement, hacktoberfest-accepted

#122 Added compile action
  .github/workflows/automation.yml
Labels: hacktoberfest-accepted
