Repository Harlem-Launch-Alliance/Catalyst-2, pull requests merged in 2022-08, with the labels that each got.

#46 Qol and fixes
  .gitignore
  README.md
Labels: documentation

#47 Platform io config
  .gitignore
  platformio.ini
Labels: enhancement

#48 Platformio documentation
  GETTING_STARTED.md
Labels: documentation

#62 Changed to HLA contributors only
  README.md
Labels: documentation

#49 added simple PR template
  pull_request_template.md
Labels: documentation

#63 issue50, changed all instances of buzzer to buzzerPin
  main/main.ino
Labels: beginner

#56 remove compiler warnings
  main/gps.h
  main/gy521_imu.h
  main/main.ino
Labels: bug, GPS
